default: &default
  adapter: mysql2
  pool: 5
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  port: 3306
  host: <%= ENV['DATABASE_HOST'] %>
  encoding: utf8
  collation: utf8_general_ci



development:
  <<: *default
  # adapter: mysql2
  database: <%= ENV['DATABASE_NAME'] %>

test:
  <<: *default
  database: <%= ENV['DATABASE_NAME'] %>


production:
  <<: *default
  database: <%= ENV['DATABASE_NAME'] %>
